### ISSUE TITLE
Android App Keep Stoping

### ISSUE THREAD

**Issue by lwangeli** [WhatsApp/stickers#164]
Hi,

Im trying to create a Stickerpach app for andriod (already created in IOS and work great), but every time I try to RUN it it load on Android and show a message that WhatsstcikerApp stopped!
 Any one have any Idea? I change everything like instruccions say but I never created an android app ever.

thank you.

**Comment by simonzhexu** [comment]
check the logcat for your app and paste the result here pls.

**Comment by lwangeli** [comment]
Hello,

I convert every PNG file to web and the app don't stop anymore but it get an error:
"Error Asset file doesn't exist... " But I can ensure you that assets is there.
Here the logicat:

`11-11 12:53:38.417 13706-13743/com.angeli.lucas.wordswhatstickers E/EntryActivity: error fetching sticker packs
    java.lang.IllegalStateException: Asset file doesn't exist. pack: Words WhatStickers Pack 1, sticker: 01_corazones.webp
        at com.example.samplestickerapp.StickerPackLoader.getStickersForPack(StickerPackLoader.java:81)
        at com.example.samplestickerapp.StickerPackLoader.fetchStickerPacks(StickerPackLoader.java:62)
        at com.example.samplestickerapp.EntryActivity$LoadListAsyncTask.doInBackground(EntryActivity.java:90)
        at com.example.samplestickerapp.EntryActivity$LoadListAsyncTask.doInBackground(EntryActivity.java:77)
        at android.os.AsyncTask$2.call(AsyncTask.java:295)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)
     Caused by: java.io.IOException: cannot read sticker asset:wordsID/01_corazones.webp
        at com.example.samplestickerapp.StickerPackLoader.fetchStickerAsset(StickerPackLoader.java:136)
        at com.example.samplestickerapp.StickerPackLoader.getStickersForPack(StickerPackLoader.java:75)
        at com.example.samplestickerapp.StickerPackLoader.fetchStickerPacks(StickerPackLoader.java:62) 
        at com.example.samplestickerapp.EntryActivity$LoadListAsyncTask.doInBackground(EntryActivity.java:90) 
        at com.example.samplestickerapp.EntryActivity$LoadListAsyncTask.doInBackground(EntryActivity.java:77) 
        at android.os.AsyncTask$2.call(AsyncTask.java:295) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
        at java.lang.Thread.run(Thread.java:818) 
11-11 12:53:38.462 13706-13706/com.angeli.lucas.wordswhatstickers E/EntryActivity: error fetching sticker packs, Asset file doesn't exist. pack: Words WhatStickers Pack 1, sticker: 01_corazones.webp
11-11 12:53:38.802 2228-4048/? E/LocSvc_IzatApiV02: E/virtual int izat_core::IzatApiV02::getBatchSize(int32_t):620]: Error : st = 4, ind.status = -1670610893
11-11 12:53:38.802 2228-4048/? E/LocSvc_IzatApiV02: E/virtual int izat_core::IzatApiV02::getBatchSize(int32_t):633]: get batching size failed.Or modem does not support batching `


Thanks for your help.

**Comment by lwangeli** [comment]
Hi There.

I find out the problem. It use the "identifier" at contents.json to locate images, so folder name need to be equal that identifier. Thanks for your help, your question made me look at logicat.

Thanks

**Comment by NehalBothra** [comment]
even i too got the same problem error:asset file doesnt exit.and i have checked the identifier and folder name too its same only but still i am getting the same error can u please help me.
![image](https://user-images.githubusercontent.com/46522615/56300155-0d032300-6153-11e9-986d-baf210cfb90d.png)

**Comment by Zandor300** [comment]
@NehalBothra Make sure the `image_file` value is correct. Your files are `1(1).webp`, `2(1).webp`, etc. Please check if this is correct. I suggest you change it to `1.webp` removing the `(1)` part. Do the same in your `contents.json` and the name of the actual files.

**Comment by NehalBothra** [comment]
thankyou soo much i got it
