### ISSUE TITLE
getting error Can't find bundle for base name messages.AndroidJpsBundle, locale en_NL

### ISSUE THREAD

**Issue by sandeepthukral** [WhatsApp/stickers#218]
I cloned the repo locally to my computer.
I opened the folder stickers (the cloned repo) in Android Studio
When I opened this project, Android Studio tells me that this project does not use the Gradel build system and I should migrate it. I ignored that error.

I followed all the steps till I reached the step of creating launcher icons. This is the time when I realized that the Android view was rather empty. Only an empty java folder and no res folder. This is not the case with the sample Application that you can create with Android Studio I made using this link (https://developer.android.com/training/basics/firstapp/index.html)

I then tried to make the module when it complained of a missing output folder. Reading the information it mentioned linking an optput folder which should contain a production and a test folder. I did that.

Now, when I made the module, I am getting this error. I looked this up on Google and could not find a resolution.

I am working on OSX 10.12.6 and using the embedded JDK/JRE

Error:Android Source Generator: Error: Can't find bundle for base name messages.AndroidJpsBundle, locale en_NL
java.util.MissingResourceException: Can't find bundle for base name messages.AndroidJpsBundle, locale en_NL
	at java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1564)
	at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1387)
	at java.util.ResourceBundle.getBundle(ResourceBundle.java:773)
	at org.jetbrains.jps.android.AndroidJpsBundle.getBundle(AndroidJpsBundle.java:22)
	at org.jetbrains.jps.android.AndroidJpsBundle.message(AndroidJpsBundle.java:32)
	at org.jetbrains.jps.android.AndroidSourceGeneratingBuilder.computeModuleDatas(AndroidSourceGeneratingBuilder.java:1276)
	at org.jetbrains.jps.android.AndroidSourceGeneratingBuilder.doBuild(AndroidSourceGeneratingBuilder.java:130)
	at org.jetbrains.jps.android.AndroidSourceGeneratingBuilder.build(AndroidSourceGeneratingBuilder.java:114)
	at org.jetbrains.jps.incremental.IncProjectBuilder.runModuleLevelBuilders(IncProjectBuilder.java:1314)
	at org.jetbrains.jps.incremental.IncProjectBuilder.runBuildersForChunk(IncProjectBuilder.java:991)
	at org.jetbrains.jps.incremental.IncProjectBuilder.buildTargetsChunk(IncProjectBuilder.java:1063)
	at org.jetbrains.jps.incremental.IncProjectBuilder.buildChunkIfAffected(IncProjectBuilder.java:954)
	at org.jetbrains.jps.incremental.IncProjectBuilder.buildChunks(IncProjectBuilder.java:787)
	at org.jetbrains.jps.incremental.IncProjectBuilder.runBuild(IncProjectBuilder.java:376)
	at org.jetbrains.jps.incremental.IncProjectBuilder.build(IncProjectBuilder.java:183)
	at org.jetbrains.jps.cmdline.BuildRunner.runBuild(BuildRunner.java:138)
	at org.jetbrains.jps.cmdline.BuildSession.runBuild(BuildSession.java:308)
	at org.jetbrains.jps.cmdline.BuildSession.run(BuildSession.java:137)
	at org.jetbrains.jps.cmdline.BuildMain$MyMessageHandler.lambda$channelRead0$0(BuildMain.java:235)
	at org.jetbrains.jps.service.impl.SharedThreadPoolImpl.lambda$executeOnPooledThread$0(SharedThreadPoolImpl.java:42)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by sandeepthukral** [comment]
This issue may be closed. User error. I opened the base of the repo (stickers) folder instead of opening the app folder (stickers/Android/app) in Android Studio. Maybe the readme needs to be updated.
