### ISSUE TITLE
[ANDROID] error with the tray icon

### ISSUE THREAD

**Issue by Zerlingg** [WhatsApp/stickers#328]
**Stickers**
My stickers do comply with the sticker requirements (512x512 and < 100 KB): YES
My tray icon does comply with the requirements (96x96 and < 50 KB): [YES
I am using WebP images for stickers.

**The problem**  
I just cant open the app

```
2018-11-29 19:27:35.233 13367-13515/com.zerlingg.weebstickerapp E/com.zerlingg.weebstickerapp: IOException when getting asset file, uri:content://com.zerlingg.weebstickerapp.stickercontentprovider/stickers_asset/19/tray.jpg
    java.io.FileNotFoundException: 19/tray.jpg
        at android.content.res.AssetManager.nativeOpenAssetFd(Native Method)
        at android.content.res.AssetManager.openFd(AssetManager.java:768)
        at com.example.samplestickerapp.StickerContentProvider.fetchFile(StickerContentProvider.java:255)
        at com.example.samplestickerapp.StickerContentProvider.getImageAsset(StickerContentProvider.java:240)
        at com.example.samplestickerapp.StickerContentProvider.openAssetFile(StickerContentProvider.java:120)
        at android.content.ContentProvider.openTypedAssetFile(ContentProvider.java:1723)
        at android.content.ContentProvider.openTypedAssetFile(ContentProvider.java:1789)
        at android.content.ContentProvider$Transport.openTypedAssetFile(ContentProvider.java:423)
        at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1458)
        at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1295)
        at android.content.ContentResolver.openInputStream(ContentResolver.java:1015)
        at com.example.samplestickerapp.StickerPackLoader.fetchStickerAsset(StickerPackLoader.java:133)
        at com.example.samplestickerapp.StickerPackValidator.verifyStickerPackValidity(StickerPackValidator.java:94)
        at com.example.samplestickerapp.StickerPackLoader.fetchStickerPacks(StickerPackLoader.java:64)
        at com.example.samplestickerapp.EntryActivity$LoadListAsyncTask.doInBackground(EntryActivity.java:135)
        at com.example.samplestickerapp.EntryActivity$LoadListAsyncTask.doInBackground(EntryActivity.java:122)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
2018-11-29 19:27:35.235 13367-13515/com.zerlingg.weebstickerapp E/EntryActivity: error fetching sticker packs
    java.lang.IllegalStateException: Cannot open tray image, tray.jpg
        at com.example.samplestickerapp.StickerPackValidator.verifyStickerPackValidity(StickerPackValidator.java:106)
        at com.example.samplestickerapp.StickerPackLoader.fetchStickerPacks(StickerPackLoader.java:64)
        at com.example.samplestickerapp.EntryActivity$LoadListAsyncTask.doInBackground(EntryActivity.java:135)
        at com.example.samplestickerapp.EntryActivity$LoadListAsyncTask.doInBackground(EntryActivity.java:122)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.io.IOException: cannot read sticker asset:19/tray.jpg
        at com.example.samplestickerapp.StickerPackLoader.fetchStickerAsset(StickerPackLoader.java:136)
        at com.example.samplestickerapp.StickerPackValidator.verifyStickerPackValidity(StickerPackValidator.java:94)
        at com.example.samplestickerapp.StickerPackLoader.fetchStickerPacks(StickerPackLoader.java:64) 
        at com.example.samplestickerapp.EntryActivity$LoadListAsyncTask.doInBackground(EntryActivity.java:135) 
        at com.example.samplestickerapp.EntryActivity$LoadListAsyncTask.doInBackground(EntryActivity.java:122) 
        at android.os.AsyncTask$2.call(AsyncTask.java:333) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764) 
2018-11-29 19:27:35.502 3455-13525/com.google.android.gms E/Ads: Error waiting for future.
    java.util.concurrent.TimeoutException
        at java.util.concurrent.FutureTask.get(FutureTask.java:206)
        at com.google.android.gms.ads.internal.util.future.g.a(:com.google.android.gms@13280022@13.2.80 (040700-211705629):14)
        at com.google.android.gms.ads.cache.i.a(:com.google.android.gms@13280022@13.2.80 (040700-211705629):5)
        at com.google.android.gms.ads.internal.request.service.c.a(:com.google.android.gms@13280022@13.2.80 (040700-211705629):40)
        at com.google.android.gms.ads.internal.request.service.c.a(:com.google.android.gms@13280022@13.2.80 (040700-211705629):198)
        at com.google.android.gms.ads.internal.request.service.f.run(:com.google.android.gms@13280022@13.2.80 (040700-211705629):1)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
2018-11-29 19:27:35.503 3455-12976/com.google.android.gms E/Ads: Error waiting for future.
    java.util.concurrent.TimeoutException
        at java.util.concurrent.FutureTask.get(FutureTask.java:206)
        at com.google.android.gms.ads.internal.util.future.g.a(:com.google.android.gms@13280022@13.2.80 (040700-211705629):14)
        at com.google.android.gms.ads.cache.i.a(:com.google.android.gms@13280022@13.2.80 (040700-211705629):5)
        at com.google.android.gms.ads.internal.request.service.c.a(:com.google.android.gms@13280022@13.2.80 (040700-211705629):40)
        at com.google.android.gms.ads.internal.request.service.c.a(:com.google.android.gms@13280022@13.2.80 (040700-211705629):198)
        at com.google.android.gms.ads.internal.request.service.f.run(:com.google.android.gms@13280022@13.2.80 (040700-211705629):1)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
```

**Comment by suriya27** [comment]
In the instructions they have said that Stickers should be in webp and Tray Icons should in png Format.
Check that.

**Comment by Zandor300** [comment]
Sticker images should be in WebP or PNG format and be < 100 KB and be exactly 512x512px.
Tray icons should be in PNG format, be < 50 KB and be exactly 96x96px.

See the following links for more info:  
https://faq.whatsapp.com/general/26000226  
https://github.com/WhatsApp/stickers/blob/master/Android/README.md#sticker-art-and-app-requirements

**Comment by Zerlingg** [comment]
it is png, it is 96x96, it is 13,4 KB

**Comment by Zerlingg** [comment]
@Zandor300

**Comment by Zandor300** [comment]
java.io.FileNotFoundException: 19/tray.jpg

Your log says so otherwise

**Comment by Zerlingg** [comment]
I mean i already tried qith both, i still have the same error even with png

**Comment by Zerlingg** [comment]
i fixed it myself nwn https://zorlonlabs.wixsite.com/ultimate the app works in most phones now i think, but i have some problems with the IOS version that i will ask later

**Comment by adityaspt** [comment]
@Zerlingg How did you fix it? Even i am having the same issue some of my stickers aren't being added, (eg 2 out of 7 stickers). In the ADB i get this error `2020-06-27 02:58:33.553 26635-26849/? E/com.idzgame.CatPun1: IOException when getting asset file, uri:content://com.idzgame.CatPun1.stickercontentprovider/stickers_asset/2/6.webp
    java.io.FileNotFoundException: This file can not be opened as a file descriptor; it is probably compressed
        at android.content.res.AssetManager.nativeOpenAssetFd(Native Method)
        at android.content.res.AssetManager.openFd(AssetManager.java:899)
        at com.plugin.unityapp.StickerContentProvider.fetchFile(StickerContentProvider.java:501)
        at com.plugin.unityapp.StickerContentProvider.getImageAsset(StickerContentProvider.java:471)
        at com.plugin.unityapp.StickerContentProvider.openAssetFile(StickerContentProvider.java:266)
        at android.content.ContentProvider.openTypedAssetFile(ContentProvider.java:1915)
        at android.content.ContentProvider.openTypedAssetFile(ContentProvider.java:1982)
        at android.content.ContentProvider$Transport.openTypedAssetFile(ContentProvider.java:511)
        at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:307)
        at android.os.Binder.execTransactInternal(Binder.java:1021)
        at android.os.Binder.execTransact(Binder.java:994)`

My other five stickers are added but these two arent seen

**Comment by adityaspt** [comment]
And of course the arent compressed or anything

**Comment by sooryaraj** [comment]
> i fixed it myself nwn https://zorlonlabs.wixsite.com/ultimate the app works in most phones now i think, but i have some problems with the IOS version that i will ask later

How did you fix this problem

**Comment by khushbuvadi** [comment]
@sooryaraj  - I have the same issue - **Exception error -->  Cannot open tray image, 20211201194216.png**. How diid you fix your problem? Can you please post your solution?

**Comment by abdelkarim1937** [comment]
![IMG-20220708-WA0001](https://user-images.githubusercontent.com/108934906/177986585-e1e0d08c-ca28-405f-a905-cb029950020b.jpg)

Please find a solution to this problem
