### ISSUE TITLE
[Android] error fetching sticker packs

### ISSUE THREAD

**Issue by remymumoh** [WhatsApp/stickers#369]
hi @simonzhexu 

When i try to load StickerPackListActivity.class, i get the error 

 ```
2018-12-28 09:49:06.637 21421-22032/com.slidy.statussaverforwhatsapp E/EntryActivity: error fetching sticker packs
    java.lang.RuntimeException: SoLoader.init() not yet called
        at com.facebook.soloader.SoLoader.assertInitialized(SoLoader.java:746)
        at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:476)
        at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:455)
        at com.facebook.imagepipeline.nativecode.StaticWebpNativeLoader.ensure(StaticWebpNativeLoader.java:32)
        at com.facebook.animated.webp.WebPImage.create(WebPImage.java:67)
        at com.slidy.statussaverforwhatsapp.stickers.StickerPackValidator.validateStickerFile(StickerPackValidator.java:129)
        at com.slidy.statussaverforwhatsapp.stickers.StickerPackValidator.validateSticker(StickerPackValidator.java:119)
        at com.slidy.statussaverforwhatsapp.stickers.StickerPackValidator.verifyStickerPackValidity(StickerPackValidator.java:108)
        at com.slidy.statussaverforwhatsapp.stickers.StickerPackLoader.fetchStickerPacks(StickerPackLoader.java:61)
        at com.slidy.statussaverforwhatsapp.stickers.EntryActivity$LoadListAsyncTask.doInBackground(EntryActivity.java:85)
        at com.slidy.statussaverforwhatsapp.stickers.EntryActivity$LoadListAsyncTask.doInBackground(EntryActivity.java:72)
        at android.os.AsyncTask$2.call(AsyncTask.java:345)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:257)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:784)
```

**Comment by simonzhexu** [comment]
Follow the directions!

There is a template when you file the issue, you need to fill in the data, otherwise, I cannot help you.

**Comment by remymumoh** [comment]
**Specifications**  
OS Level: 26(Oreo)
Device Manifacture: Huawei p20 pr0

**Stickers**
My stickers do comply with the sticker requirements (512x512 and < 100 KB): [YES]
My tray icon does comply with the requirements (96x96 and < 50 KB): [YES]
I am using [WebP/PNG] images for stickers.

**The problem**  
when i try to call this bit

```
public Pair<String, ArrayList<Sticker_packs>> doInBackground(Void... paramarray) {
            ArrayList<Sticker_packs> stickerPackList;
            try {
                final Context context = contextWeakReference.get();
                if (context != null) {
                    stickerPackList = StickerPackLoader.fetchStickerPacks(context);
                    if (stickerPackList.size() == 0) {
                        return new Pair<>("could not find any packs", null);
                    }
                    for (Sticker_packs stickerPack : stickerPackList) {
                        StickerPackValidator.verifyStickerPackValidity(context, stickerPack);
                    }
                    return new Pair<>(null, stickerPackList);
                } else {
                    return new Pair<>("could not fetch sticker packs", null);
                }
            } catch (Exception e) {
                Log.e("EntryActivity", "error fetching sticker packs", e);
                return new Pair<>(e.getMessage(), null);
            }
        }
```
i end up with this error

```
2018-12-28 09:49:06.637 21421-22032/com.slidy.statussaverforwhatsapp E/EntryActivity: error fetching sticker packs
    java.lang.RuntimeException: SoLoader.init() not yet called
        at com.facebook.soloader.SoLoader.assertInitialized(SoLoader.java:746)
        at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:476)
        at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:455)
        at com.facebook.imagepipeline.nativecode.StaticWebpNativeLoader.ensure(StaticWebpNativeLoader.java:32)
        at com.facebook.animated.webp.WebPImage.create(WebPImage.java:67)
        at com.slidy.statussaverforwhatsapp.stickers.StickerPackValidator.validateStickerFile(StickerPackValidator.java:129)
        at com.slidy.statussaverforwhatsapp.stickers.StickerPackValidator.validateSticker(StickerPackValidator.java:119)
        at com.slidy.statussaverforwhatsapp.stickers.StickerPackValidator.verifyStickerPackValidity(StickerPackValidator.java:108)
        at com.slidy.statussaverforwhatsapp.stickers.StickerPackLoader.fetchStickerPacks(StickerPackLoader.java:61)
        at com.slidy.statussaverforwhatsapp.stickers.EntryActivity$LoadListAsyncTask.doInBackground(EntryActivity.java:85)
        at com.slidy.statussaverforwhatsapp.stickers.EntryActivity$LoadListAsyncTask.doInBackground(EntryActivity.java:72)
        at android.os.AsyncTask$2.call(AsyncTask.java:345)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:257)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:784)
```
**Head of commit**
Do you have the latest commit from master?  yes i do

**How anyone may be able to reproduce the problem**  
i can share the class

**Comment by michaelcfl** [comment]
Are you trying to write your own app while using this project as a reference?
If so, you may need to initialize Fresco in your application class first.

**Comment by simonzhexu** [comment]
Yes, as @michaelcfl  mentioned, Please share your application class to further help you.

**Comment by remymumoh** [comment]
Hi @michaelcfl  yes i am trying to build my own app using this project as a reference.
this is my entry class code

`
import android.content.Context;
import android.content.Intent;
import android.os.AsyncTask;
import android.os.Bundle;
import android.support.annotation.Nullable;
import android.util.Log;
import android.util.Pair;
import android.view.WindowManager;
import android.widget.TextView;

import com.slidy.statussaverforwhatsapp.R;
import com.slidy.statussaverforwhatsapp.stickers.model.Sticker_packs;

import java.lang.ref.WeakReference;
import java.util.ArrayList;

public class EntryActivity extends BaseActivity {
    //private View progressBar;
    private LoadListAsyncTask loadListAsyncTask;


    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        getWindow().addFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN);
        setContentView(R.layout.activity_entry);
        overridePendingTransition(0, 0);
        if (getSupportActionBar() != null) {
            getSupportActionBar().hide();
        }
        //progressBar = findViewById(R.id.entry_activity_progress);
        loadListAsyncTask = new LoadListAsyncTask(EntryActivity.this);
        loadListAsyncTask.execute();
    }

    private void showStickerPack(ArrayList<Sticker_packs> stickerPackList) {
        //progressBar.setVisibility(View.GONE);
        if (stickerPackList.size() > 1) {
            final Intent intent = new Intent(this, StickerPackListActivity.class);
            intent.putParcelableArrayListExtra(StickerPackListActivity.EXTRA_STICKER_PACK_LIST_DATA, stickerPackList);
            startActivity(intent);
            finish();
            overridePendingTransition(0, 0);
        } else {
            final Intent intent = new Intent(this, StickerPackDetailsActivity.class);
            intent.putExtra(StickerPackDetailsActivity.EXTRA_SHOW_UP_BUTTON, false);
            intent.putExtra(StickerPackDetailsActivity.EXTRA_STICKER_PACK_DATA, stickerPackList.get(0));
            startActivity(intent);
            finish();
            overridePendingTransition(0, 0);
        }
    }

    private void showErrorMessage(String errorMessage) {
        //progressBar.setVisibility(View.GONE);
        Log.e("EntryActivity", "error fetching sticker packs, " + errorMessage);
        final TextView errorMessageTV = findViewById(R.id.error_message);
        errorMessageTV.setText(getString(R.string.error_message, errorMessage));
    }

    @Override
    protected void onDestroy() {
        super.onDestroy();
        if (loadListAsyncTask != null && !loadListAsyncTask.isCancelled()) {
            loadListAsyncTask.cancel(true);
        }
    }

    static class LoadListAsyncTask extends AsyncTask<Void, Void, Pair<String, ArrayList<Sticker_packs>>> {
        private final WeakReference<EntryActivity> contextWeakReference;

        LoadListAsyncTask(EntryActivity activity) {
            this.contextWeakReference = new WeakReference<>(activity);
        }

        @Override
        public Pair<String, ArrayList<Sticker_packs>> doInBackground(Void... paramarray) {
            ArrayList<Sticker_packs> stickerPackList;
            try {
                final Context context = contextWeakReference.get();
                if (context != null) {
                    stickerPackList = StickerPackLoader.fetchStickerPacks(context);
                    if (stickerPackList.size() == 0) {
                        return new Pair<>("could not find any packs", null);
                    }
                    for (Sticker_packs stickerPack : stickerPackList) {
                        StickerPackValidator.verifyStickerPackValidity(context, stickerPack);
                    }
                    return new Pair<>(null, stickerPackList);
                } else {
                    return new Pair<>("could not fetch sticker packs", null);
                }
            } catch (Exception e) {
                Log.e("EntryActivity", "error fetching sticker packs", e);
                return new Pair<>(e.getMessage(), null);
            }
        }

        @Override
        protected void onPostExecute(Pair<String, ArrayList<Sticker_packs>> stringListPair) {
            final EntryActivity entryActivity = contextWeakReference.get();
            if (entryActivity != null) {
                if (stringListPair.first != null) {
                    entryActivity.showErrorMessage(stringListPair.first);
                } else {
                    entryActivity.showStickerPack(stringListPair.second);
                }
            }
        }
    }
}`

**Comment by remymumoh** [comment]
my gradle

 implementation 'com.facebook.fresco:fresco:1.11.0'
    implementation 'com.facebook.fresco:webpsupport:1.10.0'
    implementation 'com.facebook.fresco:animated-webp:1.10.0'
    implementation 'com.google.code.gson:gson:2.2.4'

**Comment by simonzhexu** [comment]
Please test with the latest master, and let me know if you still experience issues. 

The fresco version needs to be the same by the way for all three libraries

**Comment by remymumoh** [comment]
i added this
`  SoLoader.init(this, false); `
on my entry activity and it worked
