### ISSUE TITLE
[Android] Help Request for Error 

### ISSUE THREAD

**Issue by hazarbozkurt** [WhatsApp/stickers#376]
@simonzhexu

**The problem:**
This source code is not working.
**App Source** : https://github.com/hoaipanda/StickerMakerWhatsapp

I know it's irrelevant. Sorry.
The owner of the source code is unfortunately not responding. You're my last resort.
I tried to run both signed and unsigned.
You can handle this mistake, so I wanted to apply for you.
Can anyone please help?

_Can you feedback to me after reviewing the source code?_
**Error message when I try to open the application:**
https://i.hizliresim.com/gr8ojO.png

**Crash Log (Android Studio) :**
` --------- beginning of crash
01-02 22:10:07.874 28683-28683/com.sticker.stickermakerwhatsapp E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.sticker.stickermakerwhatsapp, PID: 28683
    java.lang.RuntimeException: Unable to get provider com.sticker.stickermakerwhatsapp.StickerContentProvider: java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
        at android.app.ActivityThread.installProvider(ActivityThread.java:5004)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:4596)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4536)
        at android.app.ActivityThread.access$1500(ActivityThread.java:149)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1350)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5258)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)
     Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
        at com.sticker.stickermakerwhatsapp.StickerContentProvider.onCreate(StickerContentProvider.java:93)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:1714)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:1683)
        at android.app.ActivityThread.installProvider(ActivityThread.java:5001)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:4596) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4536) 
        at android.app.ActivityThread.access$1500(ActivityThread.java:149) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1350) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:135) 
        at android.app.ActivityThread.main(ActivityThread.java:5258) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700) 
01-02 22:10:07.876 744-1607/? W/ActivityManager:   Force finishing activity com.sticker.stickermakerwhatsapp/.activity.MainActivity
01-02 22:10:07.898 744-1607/? I/ActivityManager: SaveLog: logcontentapp: ProcessRecord{12894c9f 28683:com.sticker.stickermakerwhatsapp/u0a179}
    processNamecom.sticker.stickermakerwhatsapp
    stackTrace:java.lang.RuntimeException: Unable to get provider com.sticker.stickermakerwhatsapp.StickerContentProvider: java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
        at android.app.ActivityThread.installProvider(ActivityThread.java:5004)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:4596)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4536)
        at android.app.ActivityThread.access$1500(ActivityThread.java:149)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1350)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5258)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)
     Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
        at com.sticker.stickermakerwhatsapp.StickerContentProvider.onCreate(StickerContentProvider.java:93)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:1714)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:1683)`

**Specifications**
OS Level: [8.1]
Device : [Xiaomi Mi Note 3 - MIUI 10]

Sorry for my bad English
Best Regards.

**Comment by simonzhexu** [comment]
The error means 
public List<StickerPack> getStickerPackList() {
        if (stickerPackList == null) {

            readContentFile(Objects.requireNonNull(getContext()));
        }
        return stickerPackList;
    }
the return value is null. You need to debug and see why it is null.

**Comment by hazarbozkurt** [comment]
True, thanks for help...🤗
