### ISSUE TITLE
[Android]

### ISSUE THREAD

**Issue by Exportforce** [WhatsApp/stickers#527]
**Specifications**  
OS Version: Android 8
Device Manufacturer: Samsung Galaxy S7

**Stickers**
- [x] My stickers do comply with the sticker requirements (512x512 and < 100 KB)
- [x] My tray icon does comply with the requirements (96x96 and < 50 KB)
- [x] I am using **WebP** images for stickers.
- [ ] I am using **PNG** images for stickers.

**Problem Description**  
When installing the App all I get is "App was not installed"

**Reproduction Steps**  
Just starting the APK and hitting install.

**Head of Commit**
I am using the most recent version of this repo. All I did was importing it into the android studio, exchaning the images with the stickers I want to add and build it. But it won't let me install the app at all. I am not getting any error message except that it couldn't be installed.
[Commit hash]

**Links**  
https://drive.google.com/file/d/1xMGUFmA8G5__4Wj8ac0a2Ff9E7cI9vjA/view?usp=sharing

edit: just tested to build the example without editing and it won't work too. Same error

**Comment by ar-arvind** [comment]
Hi @Exportforce, In my device app installed successfully and there is no issues.

**Tested device**
Moto g4 plus
Android 8.1

If you try to install the `release version` of your app, `Google Play Protect` may block the app install if the package name is not recognized (If the app was not published in Play Store).

 Turn off Google Play Protect in Play Store and install the app again.

**Comment by Exportforce** [comment]
Hello,
thanks for the reply. Disabling protect worked for the install, but when I start the app, it tells me that the app keeps hanging and closes it directly.

Yes debug worked but release gave me the problem. Is there anything I can do about the app hanging and being closed?

**Comment by ar-arvind** [comment]
Is there any errors shown in logcat?

**Comment by ar-arvind** [comment]
I tested your app, the following error causes the app crash.

java.lang.RuntimeException: Unable to get provider com.example.samplestickerapp.StickerContentProvider: java.lang.RuntimeException: contents.json file has some issues: Use JsonReader.setLenient(true) to accept malformed JSON at line 3 column 4

**Comment by Exportforce** [comment]
`2019-07-20 14:09:03.989 3201-3797/? E/Sensors: inject_scontext_data: New ssp_data_injection_fd(27)
2019-07-20 14:09:04.033 6621-6675/? E/PBSessionCacheImpl: sessionId[29121029265780603] not persisted.
2019-07-20 14:09:04.164 27614-22041/? E/Launcher.WallpaperUtils: check bitmap.recycle() on releaseWallpaperDrawable
2019-07-20 14:09:05.670 27614-27614/? E/ProActivieLaunch: Sending Broadcast
2019-07-20 14:09:05.672 3705-3705/? E/ActivityManager: Checking for the Active launch isDataCleared :true, isAutoRunBlocked : false
2019-07-20 14:09:05.794 22059-22059/? E/Zygote: isWhitelistProcess - Process is Whitelisted
2019-07-20 14:09:05.856 22059-22059/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.akumanotsubasa.prochan, PID: 22059
    java.lang.RuntimeException: Unable to get provider com.example.samplestickerapp.StickerContentProvider: java.lang.RuntimeException: contents.json file has some issues: Use JsonReader.setLenient(true) to accept malformed JSON at line 3 column 4
        at android.app.ActivityThread.installProvider(ActivityThread.java:6581)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6133)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6043)
        at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1764)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6944)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
     Caused by: java.lang.RuntimeException: contents.json file has some issues: Use JsonReader.setLenient(true) to accept malformed JSON at line 3 column 4
        at com.example.samplestickerapp.StickerContentProvider.a(Unknown Source:69)
        at com.example.samplestickerapp.StickerContentProvider.a(Unknown Source:13)
        at com.example.samplestickerapp.StickerContentProvider.onCreate(Unknown Source:45)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:1927)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:1902)
        at android.app.ActivityThread.installProvider(ActivityThread.java:6578)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6133) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6043) 
        at android.app.ActivityThread.-wrap1(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1764) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6944) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374) 
     Caused by: android.util.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 3 column 4
        at android.util.JsonReader.syntaxError(JsonReader.java:1159)
        at android.util.JsonReader.checkLenient(JsonReader.java:838)
        at android.util.JsonReader.nextNonWhitespace(JsonReader.java:796)
        at android.util.JsonReader.nextInObject(JsonReader.java:652)
        at android.util.JsonReader.peek(JsonReader.java:349)
        at android.util.JsonReader.hasNext(JsonReader.java:319)
        at com.example.samplestickerapp.l.b(Unknown Source:10)
        at com.example.samplestickerapp.l.a(Unknown Source:10)
        at com.example.samplestickerapp.StickerContentProvider.a(Unknown Source:12)
        at com.example.samplestickerapp.StickerContentProvider.a(Unknown Source:13) 
        at com.example.samplestickerapp.StickerContentProvider.onCreate(Unknown Source:45) 
        at android.content.ContentProvider.attachInfo(ContentProvider.java:1927) 
        at android.content.ContentProvider.attachInfo(ContentProvider.java:1902) 
        at android.app.ActivityThread.installProvider(ActivityThread.java:6578) 
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6133) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6043) 
        at android.app.ActivityThread.-wrap1(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1764) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6944) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374) 
2019-07-20 14:09:05.888 3705-3724/? E/PhoneWindow_APM :: isCalledPackage return false
2019-07-20 14:09:06.390 6621-6675/? E/PBSessionCacheImpl: sessionId[29121029265780603] not persisted.
2019-07-20 14:09:06.502 27614-22082/? E/Launcher.WallpaperUtils: check bitmap.recycle() on releaseWallpaperDrawable
2019-07-20 14:09:06.936 9832-9872/? E/ContactsProvider_EventLog: Flush buffer to file cnt : 1 size : 1Kb duration : 5ms lastUpdatedAfter : 56671 ms mFlush_time_threasold : 2000 mCurrentSize : 1017
2019-07-20 14:09:16.344 3705-3722/? E/memtrack: Couldn't load memtrack module
2019-07-20 14:09:18.736 3303-3303/? E/audit: type=1400 audit(1563624558.724:43592): avc:  denied  { read } for  pid=21560 comm="AsyncEventManag" name="stat" dev="proc" ino=4026534934 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:proc_stat:s0 tclass=file permissive=0 SEPF_SM-G930F_8.0.0_0018 audit_filtered
2019-07-20 14:09:18.893 3705-5024/? E/memtrack: Couldn't load memtrack module
2019-07-20 14:09:18.974 3705-5030/? E/Watchdog: !@Sync 43172 [2019-07-20 14:09:18.974]
`

This is what I get when I run the app.

**Comment by Exportforce** [comment]
`{
  "android_play_store_link": "",
  "ios_app_store_link": "",
  "sticker_packs": [
    {
      "identifier": "1",
      "name": "pr0 Chan",
      "publisher": "Akuma no Tsubasa",
      "tray_image_file": "pr0chan_icon.png",
      "publisher_email":"",
      "publisher_website": "",
      "privacy_policy_website": "",
      "license_agreement_website": "",
      "stickers": [
        {
          "image_file": "1.webp"
        },        {
          "image_file": "Blussi.webp"
        },
        {
          "image_file": "Hammertime.webp"
        },
        {
          "image_file": "Minus.webp"
        },
        {
          "image_file": "Oh_neim.webp"
        },
        {
          "image_file": "p4p.webp"
        },
        {
          "image_file": "Press_F.webp"
        },
        {
          "image_file": "zomg.webp"
        }

      ]
    }
  ]
}
`

This is the file in Question. The IOS line but it is completely untouched.

**Comment by ar-arvind** [comment]
The following is the `json` file found in your app.

Remove the `forward slash` in 3rd line and run the app it will work.
```
{  
   "android_play_store_link":"",
   ///"ios_app_store_link":"",
   "sticker_packs":[  
      {  
         "identifier":"1",
         "name":"pr0 Chan",
         "publisher":"Akuma no Tsubasa",
         "tray_image_file":"pr0chan_icon.png",
         "publisher_email":"",
         "publisher_website":"",
         "privacy_policy_website":"",
         "license_agreement_website":"",
         "stickers":[  
            {  
               "image_file":"1.webp"
            },
            {  
               "image_file":"Blussi.webp"
            },
            {  
               "image_file":"Hammertime.webp"
            },
            {  
               "image_file":"Minus.webp"
            },
            {  
               "image_file":"Oh_neim.webp"
            },
            {  
               "image_file":"p4p.webp"
            },
            {  
               "image_file":"Press_F.webp"
            },
            {  
               "image_file":"zomg.webp"
            }
         ]
      }
   ]
}
```

**Comment by Exportforce** [comment]
![image](https://user-images.githubusercontent.com/627469/61579058-64bd7b80-ab00-11e9-892d-0585de8b307a.png)
there is none

**Comment by ar-arvind** [comment]
In your recompiled APK file, there is no issues with the `json` file. But the app was not installed in the device, you need to `sign` the `release version`. Sign the app and check it again.

**Comment by Exportforce** [comment]
Thanks a lot. Fun thing is, that is what I did before. Didn't change any file in the whole course. But it works now. THANKS!

**Comment by ar-arvind** [comment]
@Exportforce 👍 😃
