### ISSUE TITLE
[Android] ClassNotFoundException: com.google.wireless.android.sdk.stats.IntellijIndexingStats$Index

### ISSUE THREAD

**Issue by Superredstone** [WhatsApp/stickers#558]
I have this error when i try to build the APK

```
Error:Internal error: (java.lang.ClassNotFoundException) com.google.wireless.android.sdk.stats.IntellijIndexingStats$Index
java.lang.ClassNotFoundException: com.google.wireless.android.sdk.stats.IntellijIndexingStats$Index
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.intellij.util.indexing.counters.IndexCounters.<clinit>(IndexCounters.java:34)
	at com.intellij.util.indexing.impl.MapReduceIndex.<init>(MapReduceIndex.java:85)
	at org.jetbrains.jps.backwardRefs.index.CompilerReferenceIndex$CompilerMapReduceIndex.<init>(CompilerReferenceIndex.java:232)
	at org.jetbrains.jps.backwardRefs.index.CompilerReferenceIndex.<init>(CompilerReferenceIndex.java:79)
	at org.jetbrains.jps.backwardRefs.JavaCompilerBackwardReferenceIndex.<init>(JavaCompilerBackwardReferenceIndex.java:12)
	at org.jetbrains.jps.backwardRefs.JavaBackwardReferenceIndexWriter.initialize(JavaBackwardReferenceIndexWriter.java:79)
	at org.jetbrains.jps.incremental.java.JavaBuilder.buildStarted(JavaBuilder.java:148)
	at org.jetbrains.jps.incremental.IncProjectBuilder.runBuild(IncProjectBuilder.java:363)
	at org.jetbrains.jps.incremental.IncProjectBuilder.build(IncProjectBuilder.java:178)
	at org.jetbrains.jps.cmdline.BuildRunner.runBuild(BuildRunner.java:139)
	at org.jetbrains.jps.cmdline.BuildSession.runBuild(BuildSession.java:302)
	at org.jetbrains.jps.cmdline.BuildSession.run(BuildSession.java:135)
	at org.jetbrains.jps.cmdline.BuildMain$MyMessageHandler.lambda$channelRead0$0(BuildMain.java:228)
	at org.jetbrains.jps.service.impl.SharedThreadPoolImpl.lambda$executeOnPooledThread$0(SharedThreadPoolImpl.java:42)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

i don't know Java very well and english😁

**Comment by MarvinJWendt** [comment]
Hi @Superredstone, which Android Studio version are you using?
Have you installed the plugin `FindBugs` for Android Studio?

**Comment by Superredstone** [comment]
sorry, i m stupid, i trying to compile the folder stickers-master, Sorry again.
When i try to start the application with my sticker there is an error "Error: Asset file doesn't exist. pack: Meme sticker: smile.webp
See logcat for stack trace."
all the stickers are 512x512 in Webp

**Comment by MarvinJWendt** [comment]
Don't need to be sorry 😄 

Seems like it can't find a file, does your `contents.json` reflect your current file structure?

**Comment by Superredstone** [comment]
Thank you very much, I solved, the error was due to the stickers that had an unsupported resolution,
now another error occurs in the use of the stickers,
when I enter the section of my stickers it gives me an error "An error has occurred"

**Comment by abybaby123** [comment]
Worked for me after "invalidate cache and restart"

**Comment by yeenfei** [comment]
I'm facing the same issue (and completely new to android studio)
This is the steps I followed when i was trying to create my own WA stickers:
- download Android Studio 3.6.3 (installed using default settings on WIndows system)
- From Android Studio, New -> Project from Version Control -> Git -> https://github.com/WhatsApp/stickers
- With the example project loaded, attempt to compile via "Build" -> Make module "main"

----
I also installed the "Findbug" plugin mentioned @MarvinJWendt  via File -> Settings -> Plugins -> "QAPlug - FindBugs"

**Comment by SravyaAnne-git** [comment]
Thanks a lot. Worked for me.

**Comment by MarvinJWendt** [comment]
**Closing due to inactivity**
<sub>If this issue gets relevant again, feel free to drop a comment (mention me @MarvinJWendt) and I will reopen it.</sub>
