### ISSUE TITLE
There is a problem with this stickr pack and can't be added to whatsapp[Android]

### ISSUE THREAD

**Issue by Kenworld** [WhatsApp/stickers#598]
java.lang.IllegalArgumentException: Unknown URI: content://com.kenworldtech.stickerapp.stickercontentprovider/stickers/1
        at com.kenworldtech.stickerapp.StickerContentProvider.query(StickerContentProvider.java:114)
        at android.content.ContentProvider.query(ContentProvider.java:1060)
        at android.content.ContentProvider.query(ContentProvider.java:1152)
        at android.content.ContentProvider$Transport.query(ContentProvider.java:241)
        at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:102)
        at android.os.Binder.execTransact(Binder.java:731)
2020-01-28 04:33:45.718 7251-7251/com.kenworldtech.stickerapp E/AddStickerPackActivity: Validation failed:Unknown URI: content://com

**Comment by MarvinJWendt** [comment]
**Closing due to inactivity**
