### ISSUE TITLE
[Android]  Error adding sticker pack on whatsapp. Validation error "fd must not be null"

### ISSUE THREAD

**Issue by fulviocarmo** [WhatsApp/stickers#667]
**Stickers**
- My stickers do comply with the sticker requirements (512x512 and < 100 KB)
- My tray icon does comply with the requirements (96x96 and < 50 KB)
- I am using **WebP** images for stickers.

**Problem Description**  

I am creating a sticker functionality within my android application, however when I am sending the intent to whatsapp I am receiving the validation error with the message "fd must not be null".

What does this message mean?

How do I Fix it?

**Comment by Josepdal** [comment]
Something is wrong with your Tray Icon if i'm not wrong.

**Comment by MarvinJWendt** [comment]
**Closing due to inactivity**
<sub>If this issue gets relevant again, feel free to drop a comment (mention me @MarvinJWendt) and I will reopen it.</sub>

**Comment by krunalOrigin** [comment]
> **Stickers**
> 
> * My stickers do comply with the sticker requirements (512x512 and < 100 KB)
> * My tray icon does comply with the requirements (96x96 and < 50 KB)
> * I am using **WebP** images for stickers.
> 
> **Problem Description**
> 
> I am creating a sticker functionality within my android application, however when I am sending the intent to whatsapp I am receiving the validation error with the message "fd must not be null".
> 
> What does this message mean?
> 
> How do I Fix it?

can you solve issue ?

**Comment by Mubasherhussain059** [comment]
> **Closing due to inactivity**
> If this issue gets relevant again, feel free to drop a comment (mention me @MarvinJWendt) and I will reopen it.

hey! i am selecting image from cache dir using uri after this i am compressing image according to size and 96x96 all thing is going perferct but it cause an error
[E/DatabaseUtils: Writing exception to parcel
    java.lang.IllegalArgumentException: fd must not be null
        at android.content.res.AssetFileDescriptor.<init>(AssetFileDescriptor.java:80)
        at android.content.res.AssetFileDescriptor.<init>(AssetFileDescriptor.java:63)
        at com.myapplication.StickerContentProvider.openAssetFile(StickerContentProvider.java:140)](url)   


any solution??
