### ISSUE TITLE
[Android] App Crashed when Launched

### ISSUE THREAD

**Issue by GearFlame** [WhatsApp/stickers#723]
**Specifications**  
OS Version: [(Oppo F11) ColorOS 11 Based On Android 11]
Device Manufacturer: [Oppo]

**Stickers**
- [ X] My stickers do comply with the sticker requirements (512x512 and < 100 KB)
- [ X] My tray icon does comply with the requirements (96x96 and < 50 KB)
- [ X] I am using **WebP** images for stickers.
- [ X] I am using **PNG** images for stickers.

**Problem Description**  
My app crashed when launched.
Code:
{
  "android_play_store_link": "",
  "ios_app_store_link": "",
  "sticker_packs": [
    {
      "identifier": "1",
      "name": "Vault Boy Avatar",
      "publisher": "Frank Fabrizio",
      "tray_image_file": "atray.png",
      "image_data_version": "1",
      "avoid_cache": false,
      "publisher_email": "",
      "publisher_website": "https://fallout.bethesda.net/",
      "privacy_policy_website": "",
      "license_agreement_website": "",
      "stickers": [
        {
          "image_file": "a1.webp",
          "emojis": [
            "."
          ]
        },
        {
          "image_file": "a2.webp",
          "emojis": [
            "."
          ]
        },
        {
          "image_file": "a3.webp",
          "emojis": [
            "."
          ]
        },
        {
          "image_file": "a4.webp",
          "emojis": [
            "."
          ]
        },
        {
          "image_file": "a5.webp",
          "emojis": [
            "."
          ]
        },
        {
          "image_file": "a6.webp",
          "emojis": [
            "."
          ]
        },
        {
          "image_file": "a7.webp",
          "emojis": [
            "."
          ]
        }
      ]
    },
    {
      "identifier": "2",
      "name": "Vault Boy Emoji",
      "publisher": "Frank Fabrizio",
      "tray_image_file": "btray.png",
      "image_data_version": "1",
      "avoid_cache": false,
      "publisher_email": "",
      "publisher_website": "https://fallout.bethesda.net/",
      "privacy_policy_website": "",
      "license_agreement_website": "",
      "stickers": [
        {
          "image_file": "b01.webp",
          "emojis": [
            "."
          ]
        },
        {
          "image_file": "b02.webp",
          "emojis": [
            "."
          ]
        },
        {
          "image_file": "b03.webp",
          "emojis": [
            "."
          ]
        },
        {
          "image_file": "b04.webp",
          "emojis": [
            "."
          ]
        },
        {
          "image_file": "b05.webp",
          "emojis": [
            "."
          ]
        },
        {
          "image_file": "b06.webp",
          "emojis": [
            "."
          ]
        },
        {
          "image_file": "b07.webp",
          "emojis": [
            "."
          ]
        },
        {
          "image_file": "b08.webp",
          "emojis": [
            "."
          ]
        },
        {
          "image_file": "b09.webp",
          "emojis": [
            "."
          ]
        },
        {
          "image_file": "b10.webp",
          "emojis": [
            "."
          ]
        },
        {
          "image_file": "b11.webp",
          "emojis": [
            "."
          ]
        },
        {
          "image_file": "b12.webp",
          "emojis": [
            "."
          ]
        },
        {
          "image_file": "b13.webp",
          "emojis": [
            "."
          ]
        },
        {
          "image_file": "b14.webp",
          "emojis": [
            "."
          ]
        },
        {
          "image_file": "b15.webp",
          "emojis": [
            "."
          ]
        },
        {
          "image_file": "b16.webp",
          "emojis": [
            "."
          ]
        }
      ]
    },
    {
      "identifier": "3",
      "name": "Vault Girl Emoji",
      "publisher": "Frank Fabrizio",
      "tray_image_file": "ctray.png",
      "image_data_version": "1",
      "avoid_cache": false,
      "publisher_email": "",
      "publisher_website": "https://fallout.bethesda.net/",
      "privacy_policy_website": "",
      "license_agreement_website": "",
      "stickers": [
        {
          "image_file": "c01.webp",
          "emojis": [
            "."
          ]
        },
        {
          "image_file": "c02.webp",
          "emojis": [
            "."
          ]
        },
        {
          "image_file": "c03.webp",
          "emojis": [
            "."
          ]
        },
        {
          "image_file": "c04.webp",
          "emojis": [
            "."
          ]
        },
        {
          "image_file": "c05.webp",
          "emojis": [
            "."
          ]
        }
      ]
    },
    {
      "identifier": "4",
      "name": "Supplies",
      "publisher": "Frank Fabrizio",
      "tray_image_file": "dtray.png",
      "image_data_version": "1",
      "avoid_cache": false,
      "publisher_email": "",
      "publisher_website": "https://fallout.bethesda.net/",
      "privacy_policy_website": "",
      "license_agreement_website": "",
      "stickers": [
        {
          "image_file": "d01.webp",
          "emojis": [
            "."
          ]
        },
        {
          "image_file": "d02.webp",
          "emojis": [
            "."
          ]
        },
        {
          "image_file": "d03.webp",
          "emojis": [
            "."
          ]
        },
        {
          "image_file": "d04.webp",
          "emojis": [
            "."
          ]
        },
        {
          "image_file": "d05.webp",
          "emojis": [
            "."
          ]
        },
        {
          "image_file": "d06.webp",
          "emojis": [
            "."
          ]
        },
        {
          "image_file": "d07.webp",
          "emojis": [
            "."
          ]
        },
        {
          "image_file": "d08.webp",
          "emojis": [
            "."
          ]
        }
      ]
    },
    {
      "identifier": "5",
      "name": "Others Character",
      "publisher": "",
      "tray_image_file": "etray.png",
      "image_data_version": "1",
      "avoid_cache": false,
      "publisher_email": "",
      "publisher_website": "https://fallout.bethesda.net/",
      "privacy_policy_website": "",
      "license_agreement_website": "",
      "stickers": [
        {
          "image_file": "e01.webp",
          "emojis": [
            "."
          ]
        },
        {
          "image_file": "e02.webp",
          "emojis": [
            "."
          ]
        },
        {
          "image_file": "e03.webp",
          "emojis": [
            "."
          ]
        },
        {
          "image_file": "e04.webp",
          "emojis": [
            "."
          ]
        },
        {
          "image_file": "e05.webp",
          "emojis": [
            "."
          ]
        },
        {
          "image_file": "e06.webp",
          "emojis": [
            "."
          ]
        },
        {
          "image_file": "e07.webp",
          "emojis": [
            "."
          ]
        },
        {
          "image_file": "e08.webp",
          "emojis": [
            "."
          ]
        },
        {
          "image_file": "e09.webp",
          "emojis": [
            "."
          ]
        },
        {
          "image_file": "e10.webp",
          "emojis": [
            "."
          ]
        },
        {
          "image_file": "e11.webp",
          "emojis": [
            "."
          ]
        },
        {
          "image_file": "e12.webp",
          "emojis": [
            "."
          ]
        }
      ]
    },
    {
      "identifier": "6",
      "name": "Property",
      "publisher": "Frank Fabrizio",
      "tray_image_file": "ftray.png",
      "image_data_version": "1",
      "avoid_cache": false,
      "publisher_email": "",
      "publisher_website": "https://fallout.bethesda.net/",
      "privacy_policy_website": "",
      "license_agreement_website": "",
      "stickers": [
        {
          "image_file": "f01.webp",
          "emojis": [
            "."
          ]
        },
        {
          "image_file": "f02.webp",
          "emojis": [
            "."
          ]
        },
        {
          "image_file": "f03.webp",
          "emojis": [
            "."
          ]
        },
        {
          "image_file": "f04.webp",
          "emojis": [
            "."
          ]
        },
        {
          "image_file": "f05.webp",
          "emojis": [
            "."
          ]
        },
        {
          "image_file": "f06.webp",
          "emojis": [
            "."
          ]
        },
        {
          "image_file": "f07.webp",
          "emojis": [
            "."
          ]
        },
        {
          "image_file": "f08.webp",
          "emojis": [
            "."
          ]
        },
        {
          "image_file": "f09.webp",
          "emojis": [
            "."
          ]
        },
        {
          "image_file": "f10.webp",
          "emojis": [
            "."
          ]
        },
        {
          "image_file": "f11.webp",
          "emojis": [
            "."
          ]
        },
        {
          "image_file": "f12.webp",
          "emojis": [
            "."
          ]
        },
        {
          "image_file": "f13.webp",
          "emojis": [
            "."
          ]
        },
        {
          "image_file": "f14.webp",
          "emojis": [
            "."
          ]
        },
        {
          "image_file": "f15.webp",
          "emojis": [
            "."
          ]
        },
        {
          "image_file": "f16.webp",
          "emojis": [
            "."
          ]
        },
        {
          "image_file": "f17.webp",
          "emojis": [
            "."
          ]
        }
      ]
    }  
  ]
}

Longcat:
2020-12-22 20:32:59.580 10623-10623/? I/libc: SetHeapTaggingLevel: tag level set to 0
2020-12-22 20:32:59.587 10623-10623/? I/falloutbethesd: Late-enabling -Xcheck:jni
2020-12-22 20:32:59.617 10623-10623/? I/falloutbethesd: Unquickening 22 vdex files!
2020-12-22 20:32:59.628 10623-10623/? E/falloutbethesd: Unknown bits set in runtime_flags: 0x40000000
2020-12-22 20:32:59.706 10623-10623/? E/RefClass: java.lang.reflect.InvocationTargetException
2020-12-22 20:32:59.891 10623-10623/com.frankenstars.falloutbethesda I/oplus.android.OplusFrameworkFactoryImpl: get feature:IOplusScreenModeFeature
2020-12-22 20:32:59.891 10623-10623/com.frankenstars.falloutbethesda I/oplus.android.OplusFrameworkFactoryImpl: getOplusScreenModeFeature
2020-12-22 20:32:59.917 10623-10623/com.frankenstars.falloutbethesda D/ApplicationLoaders: Returning zygote-cached class loader: /system/framework/android.test.base.jar
2020-12-22 20:33:00.075 10623-10623/com.frankenstars.falloutbethesda D/NetworkSecurityConfig: No Network Security Config specified, using platform default
2020-12-22 20:33:00.076 10623-10623/com.frankenstars.falloutbethesda D/NetworkSecurityConfig: No Network Security Config specified, using platform default
2020-12-22 20:33:00.097 10623-10623/com.frankenstars.falloutbethesda D/AndroidRuntime: Shutting down VM
2020-12-22 20:33:00.100 10623-10623/com.frankenstars.falloutbethesda E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.frankenstars.falloutbethesda, PID: 10623
    java.lang.RuntimeException: Unable to get provider com.frankenstars.falloutbethesda.StickerContentProvider: java.lang.RuntimeException: contents.json file has some issues: publisher cannot be empty
        at android.app.ActivityThread.installProvider(ActivityThread.java:7756)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:7281)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7189)
        at android.app.ActivityThread.access$1600(ActivityThread.java:287)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2155)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:255)
        at android.app.ActivityThread.main(ActivityThread.java:8194)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:632)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
     Caused by: java.lang.RuntimeException: contents.json file has some issues: publisher cannot be empty
        at com.frankenstars.falloutbethesda.StickerContentProvider.readContentFile(StickerContentProvider.java:152)
        at com.frankenstars.falloutbethesda.StickerContentProvider.getStickerPackList(StickerContentProvider.java:158)
        at com.frankenstars.falloutbethesda.StickerContentProvider.onCreate(StickerContentProvider.java:93)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:2388)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:2358)
        at android.app.ActivityThread.installProvider(ActivityThread.java:7751)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:7281) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7189) 
        at android.app.ActivityThread.access$1600(ActivityThread.java:287) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2155) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:255) 
        at android.app.ActivityThread.main(ActivityThread.java:8194) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:632) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049) 
     Caused by: java.lang.IllegalStateException: publisher cannot be empty
        at com.frankenstars.falloutbethesda.ContentFileParser.readStickerPack(ContentFileParser.java:126)
        at com.frankenstars.falloutbethesda.ContentFileParser.readStickerPacks(ContentFileParser.java:46)
        at com.frankenstars.falloutbethesda.ContentFileParser.parseStickerPacks(ContentFileParser.java:27)
        at com.frankenstars.falloutbethesda.StickerContentProvider.readContentFile(StickerContentProvider.java:150)
        at com.frankenstars.falloutbethesda.StickerContentProvider.getStickerPackList(StickerContentProvider.java:158) 
        at com.frankenstars.falloutbethesda.StickerContentProvider.onCreate(StickerContentProvider.java:93) 
        at android.content.ContentProvider.attachInfo(ContentProvider.java:2388) 
        at android.content.ContentProvider.attachInfo(ContentProvider.java:2358) 
        at android.app.ActivityThread.installProvider(ActivityThread.java:7751) 
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:7281) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7189) 
        at android.app.ActivityThread.access$1600(ActivityThread.java:287) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2155) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:255) 
        at android.app.ActivityThread.main(ActivityThread.java:8194) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:632) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049) 
2020-12-22 20:33:00.120 10623-10623/com.frankenstars.falloutbethesda I/Process: Sending signal. PID: 10623 SIG: 9

**Comment by veskoz** [comment]
Caused by: java.lang.IllegalStateException: publisher cannot be empty
 check  this in your code
 ```
 "identifier": "5",
"name": "Others Character",
"publisher": "",
```

**Comment by GearFlame** [comment]
Ok thanks
