### ISSUE TITLE
[Android] com.facebook.ads.internal.api.AudienceNetworkAdsApi.onContentProviderCreated Stickers App

### ISSUE THREAD

**Issue by fmanoir** [WhatsApp/stickers#728]
java.lang.AbstractMethodError: abstract method "void com.facebook.ads.internal.api.AudienceNetworkAdsApi.onContentProviderCreated(android.content.Context)"
        at com.facebook.ads.internal.dynamicloading.DynamicLoaderFactory.doCallInitialize(DynamicLoaderFactory.java:160)
        at com.facebook.ads.internal.dynamicloading.DynamicLoaderFactory.access$200(DynamicLoaderFactory.java:41)
        at com.facebook.ads.internal.dynamicloading.DynamicLoaderFactory$1.run(DynamicLoaderFactory.java:122)
        at java.lang.Thread.run

**Comment by simonzhexu** [comment]
please ask in stackoverflow.
